import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { zValidator } from '@hono/zod-validator';
import { partyserverMiddleware } from 'hono-party';
import { handleUpload, handleGetAsset } from './assets';
import { handleUnfurl, unfurlQuery } from './unfurl';

// Env is generated by `wrangler types` in worker-configuration.d.ts

const app = new Hono<{ Bindings: Env }>();

app.use(
  '/api/*',
  cors({
    origin: (origin) => {
      if (!origin) return null;
      if (origin.startsWith('http://localhost:')) return origin;
      if (origin === 'https://avlo.io') return origin;
      return null;
    },
    allowMethods: ['GET', 'PUT', 'OPTIONS'],
    maxAge: 86400,
  }),
);

app.get('/api/unfurl', zValidator('query', unfurlQuery), (c) => {
  return handleUnfurl(c, c.req.valid('query').url);
});
app.put('/api/assets/:key', handleUpload);
app.get('/api/assets/:key', handleGetAsset);
app.use('*', partyserverMiddleware());

export default app;
export { RoomDurableObject } from './parties/room';
