import { Hono } from 'hono';
import { routePartykitRequest } from 'partyserver';
import assets from './routes/assets';

// Env is generated by `wrangler types` in worker-configuration.d.ts

const app = new Hono<{ Bindings: Env }>();
app.route('/api/assets', assets);
app.all('*', async (c) => {
  const res = await routePartykitRequest(c.req.raw, c.env);
  return res ?? c.text('Not Found', 404);
});

export default app;
export { RoomDurableObject } from './parties/room';
