import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { partyserverMiddleware } from 'hono-party';
import { handleUpload, handleGetAsset } from './assets';

// Env is generated by `wrangler types` in worker-configuration.d.ts

const app = new Hono<{ Bindings: Env }>();

app.use('/api/*', cors({
  origin: (origin) => {
    if (!origin) return null;
    if (origin.startsWith('http://localhost:')) return origin;
    if (origin === 'https://avlo.io') return origin;
    return null;
  },
  allowMethods: ['GET', 'PUT', 'OPTIONS'],
  maxAge: 86400,
}));

app.put('/api/assets/:key', handleUpload);
app.get('/api/assets/:key', handleGetAsset);
app.use('*', partyserverMiddleware());

export default app;
export { RoomDurableObject } from './parties/room';
