#!/usr/bin/env python3.13
"""Build the pruned, pyc-only stdlib zip for the AVLO Python runtime.

Input : dist/raw/python_stdlib.zip  (fork build output)
        config/stdlib-prune.txt     (committed prune list)
        overlay/stdlib/*.py         (sitecustomize, _avlo_runtime, ...)
Output: dist/stage/python_stdlib.zip

Must run under CPython 3.13 (pyc MAGIC must match the wasm interpreter).

Layout notes:
- zipimport loads `foo.pyc` stored NEXT TO where foo.py would live (legacy
  layout, not __pycache__) — so we compile each .py to a sibling .pyc and ship
  only the .pyc. Source lines vanish from tracebacks for stdlib frames
  (accepted: gate-pinned file+line-only contract).
- unchecked-hash invalidation: restored MEMFS mtimes are meaningless, and
  zipimport wouldn't revalidate anyway — unchecked pycs make the contract
  explicit.
- ZIP_DEFLATED(9): the zip's bytes are MEMFS-resident for the runtime's whole
  life — stored-vs-deflated is 7.2MB vs ~2MB RAM, while zipimport's per-module
  inflate is microseconds and almost every import is baked into a snapshot
  anyway. Sorted entries + fixed timestamps keep it byte-reproducible (G0).
"""

import hashlib
import io
import py_compile
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_ZIP = ROOT / "dist/raw/python_stdlib.zip"
PRUNE_TXT = ROOT / "config/stdlib-prune.txt"
OVERLAY = ROOT / "overlay/stdlib"
OUT_ZIP = ROOT / "dist/stage/python_stdlib.zip"

FIXED_DATE = (2026, 1, 1, 0, 0, 0)


def load_prune_list() -> list[str]:
    rules = []
    for line in PRUNE_TXT.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            rules.append(line)
    return rules


def is_pruned(name: str, rules: list[str]) -> bool:
    return any(
        name == r or (r.endswith("/") and name.startswith(r)) for r in rules
    )


def compile_bytes(source: bytes, arcname: str) -> bytes:
    """py -> unchecked-hash pyc bytes, via a temp file (py_compile API)."""
    import tempfile

    with tempfile.TemporaryDirectory() as td:
        src = Path(td) / "m.py"
        src.write_bytes(source)
        pyc = Path(td) / "m.pyc"
        py_compile.compile(
            str(src),
            cfile=str(pyc),
            dfile=f"/lib/python313.zip/{arcname}",  # traceback co_filename
            doraise=True,
            optimize=2,
            invalidation_mode=py_compile.PycInvalidationMode.UNCHECKED_HASH,
        )
        return pyc.read_bytes()


def main() -> None:
    if sys.version_info[:2] != (3, 13):
        sys.exit(f"need CPython 3.13 (pyc magic), got {sys.version}")
    rules = load_prune_list()
    src = zipfile.ZipFile(SRC_ZIP)

    entries: dict[str, bytes] = {}
    pruned_top: dict[str, str] = {}
    skipped = failed = 0

    # Reasons: nearest preceding comment in the prune file, per top-level name.
    reason = "stripped from the canvas Python build"
    reasons: dict[str, str] = {}
    current = reason
    for line in PRUNE_TXT.read_text().splitlines():
        line = line.strip()
        if line.startswith("# reason:"):
            current = line.removeprefix("# reason:").strip()
        elif line and not line.startswith("#"):
            top = line.split("/")[0].removesuffix(".py")
            reasons[top] = current

    for info in sorted(src.infolist(), key=lambda i: i.filename):
        name = info.filename
        if name.endswith("/"):
            continue
        if is_pruned(name, rules):
            top = name.split("/")[0].removesuffix(".py")
            pruned_top[top] = reasons.get(top, reason)
            skipped += 1
            continue
        data = src.read(name)
        if name.endswith(".py"):
            try:
                entries[name[:-3] + ".pyc"] = compile_bytes(data, name)
            except py_compile.PyCompileError as e:
                print(f"!! compile failed, shipping source: {name}: {e}")
                entries[name] = data
                failed += 1
        else:
            entries[name] = data  # data files (encodings aliases etc.)

    # Overlay modules (compiled like the rest).
    for p in sorted(OVERLAY.glob("*.py")):
        entries[p.name[:-3] + ".pyc"] = compile_bytes(p.read_bytes(), p.name)

    # Generated tombstone registry.
    lines = ["# GENERATED by pack-stdlib.py — do not edit", "PRUNED = {"]
    for top, why in sorted(pruned_top.items()):
        lines.append(f"    {top!r}: {why!r},")
    lines.append("}")
    entries["_avlo_pruned.pyc"] = compile_bytes(
        "\n".join(lines).encode(), "_avlo_pruned.py"
    )

    OUT_ZIP.parent.mkdir(parents=True, exist_ok=True)
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as out:
        for name in sorted(entries):
            zi = zipfile.ZipInfo(name, date_time=FIXED_DATE)
            zi.external_attr = 0o644 << 16
            # explicit ZipInfo bypasses the archive default → set per-entry
            out.writestr(zi, entries[name], zipfile.ZIP_DEFLATED, 9)
    OUT_ZIP.write_bytes(buf.getvalue())

    digest = hashlib.sha256(buf.getvalue()).hexdigest()
    print(
        f"packed {len(entries)} entries ({skipped} pruned, {failed} src-fallback) "
        f"{SRC_ZIP.stat().st_size:,} -> {OUT_ZIP.stat().st_size:,} bytes\n"
        f"tombstones: {', '.join(sorted(pruned_top))}\n"
        f"sha256 {digest}"
    )


if __name__ == "__main__":
    main()
