"""AVLO Python runtime site hooks.

Installed into the stripped stdlib zip. Two jobs:

1. Tombstones — a sys.meta_path finder (appended LAST so real modules always
   win) that turns imports of build-time-pruned modules into actionable
   ModuleNotFoundErrors instead of bare "No module named" mysteries. The
   registry (_avlo_pruned) is GENERATED by pack-stdlib.py/pack-package.py from
   the committed prune lists.

2. Timezone data — stdlib zoneinfo is pointed at pytz's TZif tree when the
   pytz bundle is mounted (pandas hard-requires pytz, so shipping tzdata too
   would duplicate megabytes). Lazy: only reconfigured once zoneinfo is
   actually imported (see _avlo_runtime.ensure_tzpath).
"""

import sys


class _AvloPrunedFinder:
    """Raises a friendly error for modules stripped from this build."""

    _registry = None

    @classmethod
    def _load_registry(cls):
        if cls._registry is None:
            try:
                from _avlo_pruned import PRUNED  # generated at pack time
            except ImportError:
                PRUNED = {}
            cls._registry = PRUNED
        return cls._registry

    def find_spec(self, fullname, path=None, target=None):
        registry = self._load_registry()
        top = fullname.partition(".")[0]
        reason = registry.get(fullname) or registry.get(top)
        if reason is not None:
            raise ModuleNotFoundError(
                f"'{fullname}' is not available in AVLO's Python runtime ({reason})",
                name=fullname,
            )
        return None


sys.meta_path.append(_AvloPrunedFinder())
