"""AVLO Python runtime site hooks.

Installed into the stripped stdlib zip. Three jobs:

1. Grouped extensions — a sys.meta_path finder that routes imports of C
   extensions to their bundle's single grouped side module
   (.avlo/<bundle>.so; P1.5 DSO grouping 67->4). The registry
   (_avlo_groups_<bundle>) is GENERATED by pack-package.py from
   config/dso-groups/groups.json. CPython does the rest: create_dynamic ->
   dlopen(spec.origin) -> emscripten LDSO registry hit (the executor eagerly
   dlopened the same absolute path at mount) -> dlsym PyInit_<last dotted
   component>.

2. Tombstones — a finder that turns imports of build-time-pruned modules
   into actionable ModuleNotFoundErrors instead of bare "No module named"
   mysteries. The registry (_avlo_pruned) is GENERATED by
   pack-stdlib.py/pack-package.py from the committed prune lists.

Both are APPENDED after every stock finder (PathFinder included), group
before tombstone — they only see names nothing real resolved, so stdlib
imports never pay for them.

3. Timezone data — stdlib zoneinfo is pointed at pytz's TZif tree when the
   pytz bundle is mounted (pandas hard-requires pytz, so shipping tzdata too
   would duplicate megabytes). Lazy: only reconfigured once zoneinfo is
   actually imported (see _avlo_runtime.ensure_tzpath).
"""

import sys


class _AvloGroupFinder:
    """Resolves grouped-extension imports to the bundle's group .so.

    Registry keys are EXACT dotted extension names ('pandas._libs.algos');
    values are site-packages-relative paths ('.avlo/pandas.so'), resolved
    against the registry module's own directory — prefix-agnostic, so the
    executor, corpus, harness, and prebake all get the right absolute path.
    That joined string equals the executor's mount-time dlopen string
    byte-for-byte, which is what makes the import-time dlopen an LDSO
    registry hit (refcount++, zero re-instantiation) instead of a re-load.
    Discovery mirrors _AvloPrunedFinder: per-lookup listdir of site-packages
    for _avlo_groups_* modules, cache keyed on the discovery signature.
    """

    _cache = ({}, None)  # (merged {dotted name -> abs .so path}, signature)
    _busy = False  # registry imports must not re-enter this finder

    @classmethod
    def _registries(cls):
        import os

        mods = []
        for p in sys.path:
            if not p.endswith("site-packages"):
                continue
            try:
                names = os.listdir(p)
            except OSError:
                continue
            mods.extend(
                sorted(
                    f.rsplit(".", 1)[0]
                    for f in names
                    if f.startswith("_avlo_groups_") and f.endswith((".py", ".pyc"))
                )
            )
        sig = tuple(mods)
        if cls._cache[1] == sig:
            return cls._cache[0]
        merged = {}
        cls._busy = True
        try:
            for mod in mods:
                try:
                    m = __import__(mod)
                    base = os.path.dirname(m.__file__)
                    for name, rel in m.GROUPS.items():
                        merged[name] = os.path.join(base, rel)
                except ImportError:
                    pass
        finally:
            cls._busy = False
        cls._cache = (merged, sig)
        return merged

    def find_spec(self, fullname, path=None, target=None):
        if self._busy:
            return None
        so = self._registries().get(fullname)
        if so is None:
            return None
        from importlib.machinery import ExtensionFileLoader
        from importlib.util import spec_from_file_location

        return spec_from_file_location(fullname, so, loader=ExtensionFileLoader(fullname, so))


class _AvloPrunedFinder:
    """Raises a friendly error for modules stripped from this build.

    Registry keys are EXACT dotted prune paths ('xml.sax', 'pandas.io.sas') —
    find_spec walks fullname's dotted prefixes longest-first, so a pruned
    subtree tombstones without claiming its (shipped) parents. The merged
    registry = _avlo_pruned (stdlib, pack-stdlib.py) + every
    _avlo_pruned_<bundle> module found on site-packages paths
    (pack-package.py, one per mounted bundle). Discovery re-runs per lookup:
    this finder is LAST in meta_path, so only imports every other finder
    already failed to resolve reach it — a MEMFS listdir there is noise.
    """

    _cache = ({}, None)  # (merged registry, discovery signature)
    _busy = False  # registry imports must not re-enter this finder

    @classmethod
    def _registries(cls):
        import os

        mods = ["_avlo_pruned"]
        for p in sys.path:
            if not p.endswith("site-packages"):
                continue
            try:
                names = os.listdir(p)
            except OSError:
                continue
            mods.extend(
                sorted(
                    f.rsplit(".", 1)[0]
                    for f in names
                    if f.startswith("_avlo_pruned_") and f.endswith((".py", ".pyc"))
                )
            )
        sig = tuple(mods)
        if cls._cache[1] == sig:
            return cls._cache[0]
        merged = {}
        cls._busy = True
        try:
            for mod in mods:
                try:
                    merged.update(__import__(mod).PRUNED)
                except ImportError:
                    pass  # registry module not present on this path yet
        finally:
            cls._busy = False
        cls._cache = (merged, sig)
        return merged

    def find_spec(self, fullname, path=None, target=None):
        if self._busy:
            return None
        registry = self._registries()
        name = fullname
        while name:
            reason = registry.get(name)
            if reason is not None:
                raise ModuleNotFoundError(
                    f"'{fullname}' is not available in AVLO's Python runtime ({reason})",
                    name=fullname,
                )
            name = name.rpartition(".")[0]
        return None


sys.meta_path.append(_AvloGroupFinder())
sys.meta_path.append(_AvloPrunedFinder())
