"""AVLO Python runtime site hooks.

Installed into the stripped stdlib zip. Two jobs:

1. Tombstones — a sys.meta_path finder (appended LAST so real modules always
   win) that turns imports of build-time-pruned modules into actionable
   ModuleNotFoundErrors instead of bare "No module named" mysteries. The
   registry (_avlo_pruned) is GENERATED by pack-stdlib.py/pack-package.py from
   the committed prune lists.

2. Timezone data — stdlib zoneinfo is pointed at pytz's TZif tree when the
   pytz bundle is mounted (pandas hard-requires pytz, so shipping tzdata too
   would duplicate megabytes). Lazy: only reconfigured once zoneinfo is
   actually imported (see _avlo_runtime.ensure_tzpath).
"""

import sys


class _AvloPrunedFinder:
    """Raises a friendly error for modules stripped from this build.

    Registry keys are EXACT dotted prune paths ('xml.sax', 'pandas.io.sas') —
    find_spec walks fullname's dotted prefixes longest-first, so a pruned
    subtree tombstones without claiming its (shipped) parents. The merged
    registry = _avlo_pruned (stdlib, pack-stdlib.py) + every
    _avlo_pruned_<bundle> module found on site-packages paths
    (pack-package.py, one per mounted bundle). Discovery re-runs per lookup:
    this finder is LAST in meta_path, so only imports every other finder
    already failed to resolve reach it — a MEMFS listdir there is noise.
    """

    _cache = ({}, None)  # (merged registry, discovery signature)
    _busy = False  # registry imports must not re-enter this finder

    @classmethod
    def _registries(cls):
        import os

        mods = ["_avlo_pruned"]
        for p in sys.path:
            if not p.endswith("site-packages"):
                continue
            try:
                names = os.listdir(p)
            except OSError:
                continue
            mods.extend(
                sorted(
                    f.rsplit(".", 1)[0]
                    for f in names
                    if f.startswith("_avlo_pruned_") and f.endswith((".py", ".pyc"))
                )
            )
        sig = tuple(mods)
        if cls._cache[1] == sig:
            return cls._cache[0]
        merged = {}
        cls._busy = True
        try:
            for mod in mods:
                try:
                    merged.update(__import__(mod).PRUNED)
                except ImportError:
                    pass  # baseline zip before the registry exists
        finally:
            cls._busy = False
        cls._cache = (merged, sig)
        return merged

    def find_spec(self, fullname, path=None, target=None):
        if self._busy:
            return None
        registry = self._registries()
        name = fullname
        while name:
            reason = registry.get(name)
            if reason is not None:
                raise ModuleNotFoundError(
                    f"'{fullname}' is not available in AVLO's Python runtime ({reason})",
                    name=fullname,
                )
            name = name.rpartition(".")[0]
        return None


sys.meta_path.append(_AvloPrunedFinder())
